spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import:
      - classpath:/application-oauth2.yml
      - classpath:/application-datasource.yml
logging:
  level:
    root: info
    sql: debug
